Student_project/showroom/showroom/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vechiles/',include('vechiles.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path("profile/",user_views.profilepage,name='profile'),
    
]




urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Student_project/showroom/vechiles/urls.py
from . import views
from django.urls import path

#namespace
app_name='vechiles'
urlpatterns = [
    path('start/',views.IndexClassView.as_view(),name='StartPage'),
    path('college/',views.first,name='first'),
    path('<int:pk>/',views.detailclassview.as_view(),name='details'),
    path('add/',views.add_data,name='add_data'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
]

Student_project/showroom/users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='Profilepic.jpg',upload_to='profile_pictures')
    location=models.CharField(max_length=100)

    def __strin__(self):
        return self.user.username

Student_project/showroom/vechiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Properites(models.Model):

    # reovoke the user name in properites model
    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)

    vechile_name=models.CharField(max_length=200)
    vechile_series=models.CharField(max_length=200)
    vechile_price=models.IntegerField()
    vechile_description=models.TextField()
    vechile_image=models.CharField(max_length=500,default='https://www.google.com/search?q=coming+soon+images&tbm=isch&source=iu&ictx=1&fir=c9EY_13CZrZRWM%252CZL4qJNgKW_3MbM%252C_&vet=1&usg=AI4_-kSNigLBzBYkcLD6F8TsMbtt0ISAKA&sa=X&ved=2ahUKEwi5zb_fgNjtAhVaxDgGHXYyA24Q9QF6BAgNEAE#imgrc=c9EY_13CZrZRWM')

Student_project/showroom/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username','email','password1','password2']

Student_project/showroom/vechiles/forms.py
from django import forms
from .models import Properites
class vechileForm(forms.ModelForm):
    class Meta:
        model=Properites
        fields=['vechile_name','vechile_series','vechile_price','vechile_description','vechile_image']

Student_project/showroom/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required




# Create your views here.
def register(request):
    if request.method=="POST":
        form =RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'welcome  {username},now access to your account')
            return redirect('login')
    else:
        form =RegistrationForm()
    return render(request,'users/register.html',{'form':form})

@login_required    
def profilepage(request):
    return render(request,'users/profile.html')

Student_project/showroom/vechiles/views.py
from django.shortcuts import redirect,render
from django.http import HttpResponse
from .models import Properites
from django.template import loader
from .forms import vechileForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

# Create your views here.
# sample views and learning urls
# it is a function view


def StartPage(request):
    vechile=Properites.objects.all()
    context= {
        'vechile':vechile,
    }
    return render(request,'vechiles/startpage.html',context)
    # class based view    
class IndexClassView(ListView):

    model=Properites
    template_name ='vechiles/startpage.html'
    context_object_name='vechile'


    #return HttpResponse(vechile)
def first(request):
    return HttpResponse("jantu college")

def details(request,id):
    vechile=Properites.objects.get(pk=id)
    context={
        'vechile':vechile
    }
    return render(request,'vechiles/details.html',context)


class detailclassview(DetailView):
    model=Properites
    template_name='vechiles/details.html'
    

def add_data(request):
        # create object for form class in forms.py
    form=vechileForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('vechiles:StartPage')
    return render(request,'vechiles/vechileform.html',{'form':form})
def update(request,id):
    vechile=Properites.objects.get(id=id)
    form=vechileForm(request.POST or None,instance=vechile)

    if form.is_valid():
        form.save()
        return redirect('vechiles:StartPage')
    return render(request,'vechiles/vechileform.html',{'form':form,'vechile':vechile})
def delete(request,id):
    vechile=Properites.objects.get(id=id)
    if request.method =='POST':
        vechile.delete()
        return redirect('food:StartPage')
    return render(request,'vechiles/delete.html',{'vechile':vechile})
    

Student_project/showroom/users/templates/users/login.html
<form method="POST">
    {% csrf_token%}
    {{form}}
    <button type="submit">login</button>
</form>

Student_project/showroom/users/templates/users/logout.html
<h1> you have been loged out !</h1>

Student_project/showroom/users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}">

Student_project/showroom/users/templates/users/register.html
<form method='POST'>
    {% csrf_token %}
    {{ form }}
    <button type='submit'>Register</button>
</form>

Student_project/showroom/vechiles/templates/vechiles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'vechiles/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class='navbar-brand'>
            Naveen ShowRoom
        </a>
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'vechiles:add_data' %}">add item</a>
            <a class="nav-item nav-link" href="#">delete item</a>
            <a class="nav-item nav-link" href="#">contact</a>
            <a class="nav-item nav-link" href="#">about</a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href='{% url "logout" %}'>logout</a>
                <a class="nav-item nav-link" href='{% url "profile" %}'>profile</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Sign Up</a>
            {% endif %}
        
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tag}}">{{ message}}</div>  
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}

</body>
</html>

Student_project/showroom/vechiles/templates/vechiles/delete.html
<form method ="POST">
    <h2> are you sure you want to delete {{vechile.vechile_name}}</h2>
    <button type='submit'>confirm</button>
</form>

Student_project/showroom/vechiles/templates/vechiles/details.html
{% extends 'vechiles/base.html' %}
{% block body %}

<h2>
{{object.vechile_name}}
</h2>
<h2>
{{ object.vechile_series}}
</h2>
<h4>
{{ object.vechile_price}}
</h4>
<h5>
{{object.vechile_description}}
</h5>
<a href='{ % url "vechiles:delete" vechile.vechile_id %}'>delete</a>
{% endblock %}

Student_project/showroom/vechiles/templates/vechiles/startpage.html
{% extends 'vechiles/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
</head>
<body>
    {% block body%}

    {% for item in vechile %}
    <div class='row'>
        <div class="col-md-3 ">
            <img class="card" height="170px" src="{{item.vechile_image}}">
        </div>
        
        <div class='col-md-3'>
            <h2>
               Name: {{item.vechile_name}}
                </h2>
                <h2>
                Model:{{ item.vechile_series}}
                </h2>
                <h4>
                Price:{{item.vechile_price}}
                </h4>
                <h5>
               description: {{item.vechile_description}}
                </h5>
                <div class='col-md-4 offset-md-2' > <a href="{% url 'vechiles:details' item.id %}" class='button'>Details</a></div>
        </div>
        <div class="col-md-3 ">
            <img class="card" height="170px" src="{{item.vechile_image}}">
        </div>
        <div class='col-md-3'>
            <h2>
               Name: {{item.vechile_name}}
                </h2>
                <h2>
                Model:{{ item.vechile_series}}
                </h2>
                <h4>
                Price:{{item.vechile_price}}
                </h4>
                <h5>
               description: {{item.vechile_description}}
                </h5>
                <div class='col-md-3 offset-md-2' > <a href="{% url 'vechiles:details' item.id %}" class='button'>Details</a></div>
        </div>
        
    </div>
        
    {% endfor %}
{% endblock %}
</body>
</html>
<ul>
    <li>
         <!-- remove harded codeded urls using name of urls "/vechiles/{{item.id}}"-->
       <a href="{% url 'vechiles:details' item.id %}">{{item.id}}--{{item.vechile_name}} </a>
    </li>
    
</ul>

Student_project/showroom/vechiles/templates/vechiles/vechileform.html
{% extends 'vechiles/base.html' %}
{% block body%}
<form method='POST'>
    {% csrf_token %}
    {{form}}
    <button type='submit'>Save</button>
</form>
{% endblock%}